# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/openai.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/openai.proto\x12\x07\x63hatgpt\"5\n\x0b\x43hatRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x16\n\x0e\x63onversationId\x18\x02 \x01(\t\"6\n\x0c\x43hatResponse\x12\x0b\n\x03ret\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t2F\n\x07\x43hatBot\x12;\n\nSendPrompt\x12\x14.chatgpt.ChatRequest\x1a\x15.chatgpt.ChatResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.openai_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHATREQUEST._serialized_start=31
  _CHATREQUEST._serialized_end=84
  _CHATRESPONSE._serialized_start=86
  _CHATRESPONSE._serialized_end=140
  _CHATBOT._serialized_start=142
  _CHATBOT._serialized_end=212
# @@protoc_insertion_point(module_scope)
