# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/pipeline.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/pipeline.proto\x12\x06openai\":\n\x07Message\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x1e\n\x06params\x18\x03 \x01(\x0b\x32\x0e.openai.Params\"(\n\x06\x41nswer\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\",\n\x06Params\x12\r\n\x05model\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x32\x36\n\x07\x43hatgpt\x12+\n\x04Send\x12\x0f.openai.Message\x1a\x0e.openai.Answer\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.pipeline_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=32
  _globals['_MESSAGE']._serialized_end=90
  _globals['_ANSWER']._serialized_start=92
  _globals['_ANSWER']._serialized_end=132
  _globals['_PARAMS']._serialized_start=134
  _globals['_PARAMS']._serialized_end=178
  _globals['_CHATGPT']._serialized_start=180
  _globals['_CHATGPT']._serialized_end=234
# @@protoc_insertion_point(module_scope)
